sudo: false

dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda create -n ogusa-dev python=$TRAVIS_PYTHON_VERSION
  - source activate ogusa-dev
  - conda env update -f environment.yml
  - pip install pyyaml
  - pip install pytest-pep8
  - pip install coverage
  - pip install codecov
  - python setup.py install

# command to run tests, e.g. python setup.py test
script:
  - cd ogusa; py.test -s -v -m 'not full_run and not regression'

after_success:
  - codecov
