name: ogcore-dev
channels:
- conda-forge
dependencies:
- python>=3.9.6
- ipython
- setuptools
- mkl>=2020.2
- psutil
- scipy>=1.5.0
- pandas==1.2.5
- matplotlib
- dask==2.30.0
- dask-core==2.30.0
- distributed==2.30.1
- paramtools>=0.15.0
- openpyxl
- sphinx>=3.5.4
- sphinx-book-theme>=0.1.3
- sphinx-thebe>=0.0.10
- pip
- pytest>=6.0
- pytest-pep8
- pytest-xdist
- pycodestyle
- pylint
- coverage
- requests
- xlwt
- pip:
  - jupyter-book>=0.9.1
